---
- hosts: dev
  become: True
  tasks:
    - name: Install python pip
      apt:
        name: python-pip
        state: present

    - name: Install docker
      apt:
        name: docker.io
        state: present

    - name: Start docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install docker-py python module
      pip:
        name: docker-py
        executable: pip
        state: present

    - name: Start the container
      docker_container:
        name: hariapp
        image: "uminazirah/hariapp:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8084:8080
